name: dot_seigr
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - numexpr
  - bottleneck
  - pip
  - pip:
      - flask
      - flask-cors
      - ipfshttpclient
      - requests
