name: IPFS Daemon Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  ipfs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v3  # Updated to v3
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache IPFS Binary
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/ipfs
          key: ${{ runner.os }}-ipfs-v0.18.1
          restore-keys: |
            ${{ runner.os }}-ipfs-

      - name: Install IPFS
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://dist.ipfs.io/go-ipfs/v0.18.1/go-ipfs_v0.18.1_linux-amd64.tar.gz -O /tmp/go-ipfs.tar.gz
          tar -xvzf /tmp/go-ipfs.tar.gz -C /tmp
          sudo mv /tmp/go-ipfs/ipfs /usr/local/bin/ipfs
          ipfs --version  # Verify IPFS installation

      - name: Start IPFS Daemon
        run: |
          nohup ipfs daemon &
          sleep 5  # Give it time to initialize

      - name: Check IPFS Daemon Status
        run: |
          if pgrep -x "ipfs" > /dev/null; then
            echo "IPFS daemon is running."
          else
            echo "IPFS daemon is not running."
            exit 1
          fi

      - name: Stop IPFS Daemon
        if: always()
        run: |
          pkill ipfs || true  # Terminate IPFS daemon if running
