name: IPFS Daemon Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  ipfs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check IPFS Daemon
      run: |
        if pgrep -x "ipfs" > /dev/null; then
          echo "IPFS daemon is running."
        else
          echo "IPFS daemon is not running."
          exit 1
        fi
