name: Nightly Regression Tests

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3:00 AM UTC
  workflow_dispatch:

jobs:
  nightly-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run regression tests
        run: |
          pytest --disable-warnings --maxfail=5
